# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.25)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS tfm_config psa_crypto_config psa_interface)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# The installation prefix configured by this project.
set(_IMPORT_PREFIX "F:/psoc-edge-optiga-03-secure-channel/install")

# Create imported target tfm_config
add_library(tfm_config INTERFACE IMPORTED)

set_target_properties(tfm_config PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "\$<\$<STREQUAL:,CRYPTO>:PSA_API_TEST_CRYPTO>;\$<\$<STREQUAL:,IPC>:PSA_API_TEST_IPC>;PROJECT_CONFIG_HEADER_FILE=\"F:/mtb_shared/ifx-tf-m-pse84epc2/release-v2.1.400/src/config/profile/config_profile_large.h\";TARGET_CONFIG_HEADER_FILE=\"F:/mtb_shared/ifx-tf-m-pse84epc2/release-v2.1.400/src/config/../platform/ext/target/infineon/pse84/config_tfm_target.h\";\$<\$<OR:\$<BOOL:ON>,\$<BOOL:0>>:CONFIG_TFM_CONNECTION_POOL_ENABLE>;TFM_PARTITION_LOG_LEVEL=TFM_PARTITION_LOG_LEVEL_DEBUG;\$<\$<BOOL:ON>:TFM_SP_LOG_RAW_ENABLED>;TFM_PARTITION_CRYPTO;TFM_PARTITION_INITIAL_ATTESTATION;TFM_PARTITION_PROTECTED_STORAGE;TFM_PARTITION_INTERNAL_TRUSTED_STORAGE;TFM_PARTITION_PLATFORM;TFM_PARTITION_NS_AGENT_TZ;\$<\$<STREQUAL:,IPC>:PSA_API_TEST_IPC>;\$<\$<STREQUAL:PSA_ALG_CCM,PSA_ALG_GCM>:PS_CRYPTO_AEAD_ALG_GCM>;\$<\$<STREQUAL:PSA_ALG_CCM,PSA_ALG_CCM>:PS_CRYPTO_AEAD_ALG_CCM>;\$<\$<BOOL:ON>:PS_ENCRYPTION>;PS_AES_KEY_USAGE_LIMIT=0;IFX_MBEDTLS_ACCELERATION_ENABLED=1;IFX_BSP_CONFIG_HEADER_FILE=\"F:/mtb_shared/ifx-tf-m-pse84epc2/release-v2.1.400/src/platform/ext/target/infineon/pse84/epc2/board/KIT_PSOCE84_EVK/config_bsp.h\";\$<\$<BOOL:ON>:IFX_CM33_NS_PRESENT=1>;\$<\$<BOOL:ON>:IFX_CM55_NS_PRESENT=1>;\$<\$<BOOL:>:IFX_PARTITION_SE_IPC_SERVICE>;IFX_SE_IPC_SERVICE_FULL=\$<STREQUAL:BASE,FULL>;IFX_SE_IPC_SERVICE_BASE=\$<STREQUAL:BASE,BASE>;IFX_DRIVER_FLASH_PROG_BUF_ON_STACK=\$<BOOL:>;IFX_DRIVER_FLASH_SINGLE_INSTANCE=\$<BOOL:>;TARGET_APP_KIT_PSE84_EVAL_EPC2;TEST_NS_IFX_CODE_COVERAGE=\$<BOOL:OFF>;\$<\$<BOOL:OFF>:IFX_PRINT_CORE_PREFIX=1>;\$<\$<BOOL:ON>:IFX_MTB_SRF>;TEST_NS_IFX_ISOLATION_TEST=\$<BOOL:>;\$<\$<BOOL:>:TEST_NS_IFX_IRQ_TEST_MASKED=1>;\$<\$<BOOL:>:TEST_NS_IFX_IRQ_TEST_UNMASKED=1>;\$<\$<BOOL:>:TEST_NS_IFX_CRYPTO_BENCHMARK=1>;\$<\$<BOOL:>:TEST_NS_IFX_FRAMEWORK=1>;\$<\$<BOOL:>:PSA_API_TEST_ENABLED>;DUMP_TOKEN=1;\$<\$<BOOL:ON>:IFX_MTB_MAILBOX=1>"
)

# Create imported target psa_crypto_config
add_library(psa_crypto_config INTERFACE IMPORTED)

set_target_properties(psa_crypto_config PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "MBEDTLS_PSA_CRYPTO_CONFIG_FILE=\"F:/mtb_shared/ifx-tf-m-pse84epc2/release-v2.1.400/src/lib/ext/mbedcrypto/mbedcrypto_config/crypto_config_profile_large.h\";MBEDTLS_CONFIG_FILE=\"F:/mtb_shared/ifx-tf-m-pse84epc2/release-v2.1.400/src/lib/ext/mbedcrypto/mbedcrypto_config/tfm_mbedcrypto_config_profile_large_client.h\";\$<\$<BOOL:>:MBEDTLS_PSA_CRYPTO_PLATFORM_FILE=\"\">;\$<\$<BOOL:F:/mtb_shared/ifx-tf-m-pse84epc2/release-v2.1.400/src/platform/ext/target/infineon/pse84/../common/spe/services/crypto/mbedtls_accel_configs/crypto_hw_mxcrypto_config.h>:CRYPTO_HW_ACCELERATOR_CONFIG=\"F:/mtb_shared/ifx-tf-m-pse84epc2/release-v2.1.400/src/platform/ext/target/infineon/pse84/../common/spe/services/crypto/mbedtls_accel_configs/crypto_hw_mxcrypto_config.h\">"
)

# Create imported target psa_interface
add_library(psa_interface INTERFACE IMPORTED)

set_target_properties(psa_interface PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "\$<\$<BOOL:>:CONFIG_TFM_ENABLE_CTX_MGMT>;\$<\$<BOOL:2>:TFM_ISOLATION_LEVEL=2>;\$<\$<BOOL:ON>:CONFIG_TFM_USE_TRUSTZONE>;\$<\$<BOOL:OFF>:TFM_MULTI_CORE_TOPOLOGY>;\$<\$<BOOL:ON>:CONFIG_TFM_PARTITION_META>;\$<\$<BOOL:>:TFM_MULTI_CORE_TEST>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/interface/include"
  INTERFACE_LINK_LIBRARIES "tfm_config"
)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/spe_export-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
    if(NOT EXISTS "${_cmake_file}")
      message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
